config {
  type: "table",
  schema: "staging_okticket",
  name: "stg_okticket_company"
}

SELECT
    CAST(id AS INT64) AS id,
    name,
    cif,
    fiscal_address,
    postal_code,
    city,
    logo_path,
    CAST(contact_number AS INT64) AS contact_number,
    contact_email,
    CAST(license_id AS INT64) AS license_id,
    CAST(max_users AS INT64) AS max_users,
    CAST(type_id AS INT64) AS type_id,
    CAST(created_at AS TIMESTAMP) AS created_at,
    CAST(updated_at AS TIMESTAMP) AS updated_at,
    CAST(deleted_at AS STRING) AS deleted_at,
    CAST(workflow_id AS INT64) AS workflow_id,
    CAST(advance_payment_workflow_id AS INT64) AS advance_payment_workflow_id,
    CAST(travel_workflow_id AS INT64) AS travel_workflow_id,
    language,
    pdf_logo,
    date_filter_code,
    CAST(sales AS FLOAT64) AS sales,
    CAST(employee_number AS FLOAT64) AS employee_number,
    CAST(company_size AS INT64) AS company_size,
    country_id,
    currency,
    distance_unit,
    CAST(distance_unit_price AS FLOAT64) AS distance_unit_price,
    CAST(group_id AS INT64) AS group_id,
    custom_id
FROM ${ref('okticket_company_raw')}

