config {
  type: "table",
  schema: "staging_okticket",
  name: "stg_okticket_users",
}

SELECT
  CAST(id AS INT64) AS id,
  name,
  email,
  CAST(id_role AS INT64) AS id_role,
  CAST(status_id AS INT64) AS status_id,
  CAST(company_type_id AS INT64) AS company_type_id,
  currency,
  CAST(NULLIF(distance_unit_price, '') AS FLOAT64) AS distance_unit_price,
  app_version,
  CAST(legal_texts_version AS INT64) AS legal_texts_version,
  CAST(pop_checked AS INT64) AS pop_checked,
  CAST(tyc_checked AS INT64) AS tyc_checked,
  CAST(NULLIF(created_at, '') AS DATETIME) AS created_at,
  CAST(NULLIF(updated_at, '') AS DATETIME) AS updated_at,
  CAST(NULLIF(deleted_at, '') AS DATETIME) AS deleted_at,
  CAST(active_company AS INT64) AS active_company,
  CAST(active_department AS INT64) AS active_department,
  custom_id,
  custom_id_2,
  custom_id_3,
  language,
  CASE WHEN active = 'True' THEN TRUE ELSE FALSE END AS active,
  CAST(NULLIF(last_login_date, '') AS DATETIME) AS last_login_date,
  CAST(NULLIF(login_error_count, '') AS FLOAT64) AS login_error_count,
  CAST(skip_sso AS INT64) AS skip_sso,
  CAST(NULLIF(companies, '') AS INT64) AS companies
FROM ${ref('okticket_users_raw')}
